# Generated by Django 3.1.7 on 2021-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20210319_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
