# Generated by Django 3.1.2 on 2021-04-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_remove_doctoruser_doctor_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_num',
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='specialty',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='sub_specialty',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profile_photos'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.doctoruser')),
            ],
        ),
    ]
