# Generated by Django 3.1.7 on 2021-04-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
