# Generated by Django 3.1.7 on 2021-04-21 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_appointment_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basicapp.address'),
        ),
    ]
