# Generated by Django 3.1.7 on 2021-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_appointment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
