# Generated by Django 3.1.7 on 2021-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_auto_20210421_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
