# Generated by Django 3.1.7 on 2021-04-29 19:19

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_auto_20210425_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
