# Generated by Django 3.1.2 on 2021-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
