# Generated by Django 3.1.7 on 2021-05-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0014_auto_20210505_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineappointment',
            name='duration_number',
        ),
        migrations.AlterField(
            model_name='onlineappointment',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.duration'),
        ),
    ]
