# Generated by Django 3.1.7 on 2021-05-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0016_auto_20210512_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineappointment',
            name='changed_time',
        ),
        migrations.AlterField(
            model_name='onlineappointment',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.duration'),
        ),
    ]
